### ISSUE TITLE
[Bug]: OCR missing?

### ISSUE THREAD

**Issue by MarcRene71** [yfedoseev/pdf_oxide#204]
### Bug Description

According to your documentation:

`text = doc.extract_text_ocr(0)`

result (at least from python) is: AttributeError: 'builtins.PdfDocument' object has no attribute 'extract_text_ocr'. Did you mean: 'extract_text'?

### Steps to Reproduce

pip install pdf_oxide

from pdf_oxide import PdfDocument

doc = PdfDocument("scanned.pdf")
text = doc.extract_text_ocr(0)
print(text)

### Expected Behavior

Text output from OCR

### Actual Behavior

Error Message: AttributeError: 'builtins.PdfDocument' object has no attribute 'extract_text_ocr'. Did you mean: 'extract_text'?

### Environment

- **OS**: Windows 11
- **Rust version**:  n/a
- **pdf_oxide version**: 0.3.13
- **Python version** (if using Python bindings): 3.13.11

### Code Sample

```rust
from pdf_oxide import PdfDocument

doc = PdfDocument("scanned.pdf")
text = doc.extract_text_ocr(0)
print(text)
```

### Error Messages / Logs

```shell
AttributeError: 'builtins.PdfDocument' object has no attribute 'extract_text_ocr'. Did you mean: 'extract_text'?
```

### Checklist

- [x] I have searched existing issues to make sure this is not a duplicate
- [x] I have provided all required information above
- [x] I am using the latest version of pdf_oxide

**Comment by potatochipcoconut** [comment]
@yfedoseev getting same error when I try to test out the OCR feature from the docs in python

**Comment by potatochipcoconut** [comment]
```
pip install pdf_oxide[ocr]
zsh: no matches found: pdf_oxide[ocr]
```

**Comment by yfedoseev** [comment]
@potatochipcoconut the zsh error is a shell quoting issue — square brackets are glob characters in zsh. Wrap the package name in single quotes:

```sh
pip install 'pdf_oxide[ocr]'
```

This works in zsh, bash, and fish. The pip docs mention it but it trips up a lot of people.

@MarcRene71 if you're still getting "OCR feature not enabled" after that install, please share your Python version and OS — the OCR wheel ships as a separate binary and occasionally the wrong wheel gets selected on non-standard setups.

Adding a note to the OCR installation docs so this is the first thing shown.

**Comment by MarcRene71** [comment]
Tried it on my home-PC (Win 11, Python 3.14,4, installed with "pip install pdf_oxide[ocr]") and it works fine.
Will check on my office-PC on Monday :)

Update: works on my officePC (Python 3.13.13), too. the OCR result is empty, but at least no error :)

**Comment by potatochipcoconut** [comment]
bah, whoops! good catch
