### ISSUE TITLE
[Bug]: pdf_oxide 0.3.78 fails to compile with office_oxide 0.1.12 (missing field defined_names in DocumentIR

### ISSUE THREAD

**Issue by cemoktra** [yfedoseev/pdf_oxide#1597]
### Bug Description

pdf_oxide 0.3.78 declares office_oxide = "0.1.9", so Cargo resolves the newest 0.1.x release. office_oxide 0.1.12 (2026-09-21) added the public field DocumentIR::defined_names. Under Cargo’s rules 0.1.11 → 0.1.12 is a compatible update, so any fresh build or cargo update of a project that depends on pdf_oxide breaks without the user changing anything.

### Steps to Reproduce

```
cargo new repro && cd repro
cargo add pdf_oxide@0.3.78
cargo build
```

### Expected Behavior

pdf_oxide 0.3.78 compiles with every office_oxide version its dependency requirement allows, including 0.1.12.

### Actual Behavior

```
error[E0063]: missing field `defined_names` in initializer of `DocumentIR`
   --> pdf_oxide-0.3.78/src/converters/pdf_to_ir.rs:194:8
    |
194 |     Ok(DocumentIR { metadata, sections })
    |        ^^^^^^^^^^ missing `defined_names`
```

Pinning office_oxide to 0.1.11 makes it build again:

### Environment

- pdf_oxide 0.3.78 (default features)
- office_oxide 0.1.12 fails, 0.1.11 builds
- rustc 1.98.1, cargo 1.98.1
- Linux (x86_64)

### Code Sample

```rust

```

### Error Messages / Logs

```shell

```

### Checklist

- [x] I have searched existing issues to make sure this is not a duplicate
- [x] I can reproduce this reliably and have given the exact steps
- [x] I have not attached any copyrighted or third-party PDF
- [x] This report is written in my own words (not AI-generated)
- [x] I am using the latest version of pdf_oxide
