### ISSUE TITLE
The ocr feature does not compile: OcrSpan::to_text_span misses TextSpan's two newest fields

### ISSUE THREAD

**Issue by yfedoseev** [yfedoseev/pdf_oxide#1548]
## Summary

`cargo build --features ocr` does not compile on `release/v0.3.79`:

```
error[E0063]: missing fields `bdc_seq` and `bidi_settled` in initializer of `text_block::TextSpan`
  --> src/ocr/engine.rs:59:9
```

`OcrSpan::to_text_span` builds a `TextSpan` by naming every field. Two fields were added to `TextSpan` on the branch — `bdc_seq` (a tagged cell keeps the first BDC of its /MCID) and `bidi_settled` (#1526) — and the 21 literal sites under the default features were updated; the one under `#[cfg(feature = "ocr")]` was not, because nothing on the branch compiles that feature. `ocr-tract` shares the file.

## Why it was not seen

The sweep tiers are `default`, `rendering`, `signatures` (`fips,icc` and `ml` on demand); no tier builds `ocr`. CONTRIBUTING §7's "green across the whole feature matrix" covers it in words only.

## Expected

The `ocr` and `ocr-tract` features build; a unit test under the feature pins the OCR span's values for the two fields (no marked content, direction not settled from glyph positions), so a further field added to `TextSpan` fails here at the same time it fails under the default features; and the `ocr` feature is checked in the release sweep.

Found while compiling the `ocr`-gated test files converted for #1348.

**Comment by yfedoseev** [comment]
Fixed in c789dd9c on release/v0.3.79: the literal names both fields, a unit test under the feature (`test_an_ocr_span_declares_no_marked_content_and_no_settled_direction`) pins them, the seven `ocr`-gated integration test binaries build and run (5 passed, 14 ignored without the corpus), and `cargo check --features ocr-tract` is clean. The `ocr` tier is in the release sweep script from sweep #16 on. CHANGELOG entry under [0.3.79].
